name: Release

on:
  push:
    branches: [ main ]
    tags:
      - 'v*'
  pull_request:
    branches: [ main ]

jobs:
  build-and-release:
    name: Build and Release
    runs-on: ${{ matrix.os }}
    if: startsWith(github.ref, 'refs/tags/')
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            artifact_name: bilistream
            asset_name: bilistream-linux-x86_64
          - os: ubuntu-latest
            artifact_name: bilistream
            asset_name: bilistream-linux-aarch64
            target: aarch64-unknown-linux-gnu
          - os: windows-latest
            artifact_name: bilistream.exe
            asset_name: bilistream-windows-x86_64.exe
          - os: windows-latest
            artifact_name: bilistream.exe
            asset_name: bilistream-windows-aarch64.exe
            target: aarch64-pc-windows-msvc
          - os: macOS-latest
            artifact_name: bilistream
            asset_name: bilistream-macos-x86_64
          - os: macOS-latest
            artifact_name: bilistream
            asset_name: bilistream-macos-aarch64
            target: aarch64-apple-darwin
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}
      - name: Install dependencies (Ubuntu)
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y libssl-dev pkg-config
          if [ "${{ matrix.target }}" = "aarch64-unknown-linux-gnu" ]; then
            sudo apt-get install -y gcc-aarch64-linux-gnu
            sudo ln -s /usr/bin/aarch64-linux-gnu-gcc /usr/bin/aarch64-linux-gnu-cc
          fi
      - name: Install dependencies (macOS)
        if: runner.os == 'macOS'
        run: brew install openssl pkg-config
      - name: Install dependencies (Windows)
        if: runner.os == 'Windows'
        run: |
          choco install openssl pkgconfiglite
          echo "OPENSSL_DIR=C:\Program Files\OpenSSL-Win64" >> $GITHUB_ENV
          echo "PKG_CONFIG_PATH=C:\Program Files\OpenSSL-Win64\lib\pkgconfig" >> $GITHUB_ENV
      - name: Build
        run: |
          if [ "${{ matrix.target }}" ]; then
            export CARGO_TARGET_AARCH64_UNKNOWN_LINUX_GNU_LINKER=aarch64-linux-gnu-gcc
            export CC_aarch64_unknown_linux_gnu=aarch64-linux-gnu-gcc
            export OPENSSL_DIR=/usr/aarch64-linux-gnu
            cargo build --release --target ${{ matrix.target }}
          else
            cargo build --release
          fi
        shell: bash
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false
        if: matrix.os == 'ubuntu-latest' && !matrix.target
      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ${{ matrix.target && format('./target/{}/release/{}', matrix.target, matrix.artifact_name) || format('./target/release/{}', matrix.artifact_name) }}
          asset_name: ${{ matrix.asset_name }}
          asset_content_type: application/octet-stream